name: Daily Sync of CSA branches

on:
    schedule:
        - cron: "0 0 * * *" # Runs once a day at midnight
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    sync:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - local_branch: csa
                      upstream_branch: master
                    - local_branch: csa-v1.5-branch
                      upstream_branch: v1.5-branch

        steps:
            - name: Generate token for the workflow
              id: generate_token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ vars.SILABSSW_MATTER_CI_BOT_APP_ID }}
                  private-key:
                      ${{ secrets.SILABSSW_MATTER_CI_BOT_APP_PRIVATE_KEY }}
            - name: Mask the generated token
              run: echo "::add-mask::${{ steps.generate_token.outputs.token }}"

            - name: Checkout matter_sdk::${{ matrix.local_branch }} branch
              uses: actions/checkout@v4
              with:
                  repository: SiliconLabsSoftware/matter_sdk
                  ref: ${{ matrix.local_branch }}
                  token: ${{ steps.generate_token.outputs.token }}

            - name: Add CSA repository remote
              run: |
                  git remote add upstream https://github.com/project-chip/connectedhomeip.git

            - name: Update the ${{ matrix.local_branch }} branch locally
              run: git pull upstream ${{ matrix.upstream_branch }}

            - name: Push the updated ${{ matrix.local_branch }} branch to the remote
              run: |
                  git push origin ${{ matrix.local_branch }}

